// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obras.Api.Data;

#nullable disable

namespace Obras.Api.Data.Migrations
{
    [DbContext(typeof(MaterialContext))]
    [Migration("20260305183328_JefeFinal44")]
    partial class JefeFinal44
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Obras.Api.Models.DetalleRequerimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequerimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequerimientoId");

                    b.ToTable("DetallesRequerimiento");
                });

            modelBuilder.Entity("Obras.Api.Models.Jefe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jefes");
                });

            modelBuilder.Entity("Obras.Api.Models.MaterialAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("MaterialesAlmacen");
                });

            modelBuilder.Entity("Obras.Api.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Obras.Api.Models.Requerimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Requerimientos");
                });

            modelBuilder.Entity("Obras.Api.Models.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioAccesoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAccesoId")
                        .IsUnique();

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("Obras.Api.Models.UsuarioAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsuariosAcceso");
                });

            modelBuilder.Entity("ProyectoTrabajador", b =>
                {
                    b.Property<int>("ProyectosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrabajadoresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectosId", "TrabajadoresId");

                    b.HasIndex("TrabajadoresId");

                    b.ToTable("TrabajadorProyecto", (string)null);
                });

            modelBuilder.Entity("Obras.Api.Models.DetalleRequerimiento", b =>
                {
                    b.HasOne("Obras.Api.Models.Requerimiento", "Requerimiento")
                        .WithMany("Detalles")
                        .HasForeignKey("RequerimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requerimiento");
                });

            modelBuilder.Entity("Obras.Api.Models.MaterialAlmacen", b =>
                {
                    b.HasOne("Obras.Api.Models.Proyecto", "Proyecto")
                        .WithMany("CatalogoAlmacen")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Obras.Api.Models.Proyecto", b =>
                {
                    b.HasOne("Obras.Api.Models.UsuarioAcceso", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Obras.Api.Models.Requerimiento", b =>
                {
                    b.HasOne("Obras.Api.Models.Proyecto", "Proyecto")
                        .WithMany("Requerimientos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obras.Api.Models.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("Obras.Api.Models.Trabajador", b =>
                {
                    b.HasOne("Obras.Api.Models.UsuarioAcceso", "UsuarioAcceso")
                        .WithOne("Trabajador")
                        .HasForeignKey("Obras.Api.Models.Trabajador", "UsuarioAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAcceso");
                });

            modelBuilder.Entity("ProyectoTrabajador", b =>
                {
                    b.HasOne("Obras.Api.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obras.Api.Models.Trabajador", null)
                        .WithMany()
                        .HasForeignKey("TrabajadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obras.Api.Models.Proyecto", b =>
                {
                    b.Navigation("CatalogoAlmacen");

                    b.Navigation("Requerimientos");
                });

            modelBuilder.Entity("Obras.Api.Models.Requerimiento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Obras.Api.Models.UsuarioAcceso", b =>
                {
                    b.Navigation("Trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
